#!/usr/bin/env python3

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ============================================================
# 1. SETUP & PATHS
# ============================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "output")
FIGURE_DIR = os.path.join(PROJECT_ROOT, "figures")

# FIXED: Synchronized with the correct filename generated by the fitting step
CSV_FILE = os.path.join(OUTPUT_DIR, "02_lorentzian_summary.csv")
TXT_OUT = os.path.join(OUTPUT_DIR, "03a_dnu_fit_equations.txt")

# ============================================================
# 2. CONFIGURATIONS & SETTINGS
# ============================================================
# Trusted low-T points (Determined from Rex/LW < 10% to capture pure linearity)
FIT_TEMPS_600 = [285, 288, 291, 293, 296]
FIT_TEMPS_800 = [285, 288, 293, 298]

COLOR_600 = "#1f77b4"   # Classic Blue
COLOR_800 = "#c47a00"   # Dark Yellow-Orange
USE_SEM = False

# ============================================================
# PLOT STYLE SETTINGS
# ============================================================
plt.rcParams.update({
    "axes.labelsize": 22,
    "xtick.labelsize": 18,
    "ytick.labelsize": 18,
    "legend.fontsize": 20,
    "axes.linewidth": 1.5,
    "xtick.major.width": 1.5,
    "ytick.major.width": 1.5,
    "xtick.major.size": 6,
    "ytick.major.size": 6,
    "pdf.fonttype": 42,
    "ps.fonttype": 42
})

# ============================================================
# 3. DATA LOADING & AGGREGATION
# ============================================================
if not os.path.exists(CSV_FILE):
    print(f"❌ Error: {CSV_FILE} not found. Run your Lorentzian fitter script first.")
    import sys; sys.exit(1)

df = pd.read_csv(CSV_FILE)

# Aggregate replicate sets smoothly
summary = df.groupby(["Field", "Temp"], as_index=False).agg({"dnu_Hz": ["mean", "std", "count"]})
summary.columns = ["Field", "Temp", "dnu_mean", "dnu_std", "n"]

# Calculate error constraints
summary["dnu_sem"] = summary["dnu_std"] / np.sqrt(summary["n"])
summary["dnu_err"] = summary["dnu_sem"] if USE_SEM else summary["dnu_std"]

# Map dynamic validation masks
summary["used"] = False
summary.loc[((summary["Field"] == 600) & (summary["Temp"].isin(FIT_TEMPS_600))), "used"] = True
summary.loc[((summary["Field"] == 800) & (summary["Temp"].isin(FIT_TEMPS_800))), "used"] = True

fit600 = summary[(summary["Field"] == 600) & (summary["used"])]
fit800 = summary[(summary["Field"] == 800) & (summary["used"])]

# ============================================================
# 4. SHARED-SLOPE LSQ REGRESSION ENGINE
# ============================================================
# Core Matrix Formulation:
# dnu600(T) = a600 + b*(T-298)
# dnu800(T) = a800 + b*(T-298)
X, Y = [], []

for _, row in fit600.iterrows():
    X.append([1, 0, (row["Temp"] - 298.0)])
    Y.append(row["dnu_mean"])

for _, row in fit800.iterrows():
    X.append([0, 1, (row["Temp"] - 298.0)])
    Y.append(row["dnu_mean"])

X, Y = np.array(X), np.array(Y)
params, _, _, _ = np.linalg.lstsq(X, Y, rcond=None)
a600, a800, slope = params

# ============================================================
# 5. WRITE SYSTEM LOGS (Sanitized ASCII text strings)
# ============================================================
print("\n" + "="*60)
print("              GLOBAL MULTI-FIELD dnu(T) FIT")
print("="*60)
print(f"  dnu600(T) = {a600:.3f} + ({slope:.4f}) * (T-298)")
print(f"  dnu800(T) = {a800:.3f} + ({slope:.4f}) * (T-298)")
print("="*60)

with open(TXT_OUT, "w") as f:
    f.write("="*60 + "\n")
    f.write("GLOBAL MULTI-FIELD dnu(T) FIT\n")
    f.write("="*60 + "\n\n")
    f.write(f"Error bar layout = {'SEM' if USE_SEM else 'SD'}\n\n")
    f.write(f"dnu600(T) = {a600:.4f} + ({slope:.4f}) * (T-298)\n")
    f.write(f"dnu800(T) = {a800:.4f} + ({slope:.4f}) * (T-298)\n")

# ============================================================
# 6. RENDER REPOSITORY VISUALIZATIONS
# ============================================================
T_plot = np.linspace(284, 316, 400)
fitline600 = a600 + slope * (T_plot - 298.0)
fitline800 = a800 + slope * (T_plot - 298.0)

used600 = summary[(summary["Field"] == 600) & (summary["used"])]
excl600 = summary[(summary["Field"] == 600) & (~summary["used"])]
used800 = summary[(summary["Field"] == 800) & (summary["used"])]
excl800 = summary[(summary["Field"] == 800) & (~summary["used"])]

fig, ax = plt.subplots(figsize=(8, 6.0))

# 600 MHz Traces (Included vs Excluded)
ax.errorbar(used600["Temp"], used600["dnu_mean"], yerr=used600["dnu_err"],
            fmt='o', color=COLOR_600, ms=10, lw=2, capsize=4, label="600 MHz")
ax.errorbar(excl600["Temp"], excl600["dnu_mean"], yerr=excl600["dnu_err"],
            fmt='o', markerfacecolor='none', markeredgecolor=COLOR_600,
            markeredgewidth=2, ecolor=COLOR_600, ms=10, lw=2, capsize=4)

# 800 MHz Traces (Included vs Excluded)
ax.errorbar(used800["Temp"], used800["dnu_mean"], yerr=used800["dnu_err"],
            fmt='o', color=COLOR_800, ms=10, lw=2, capsize=4, label="800 MHz")
ax.errorbar(excl800["Temp"], excl800["dnu_mean"], yerr=excl800["dnu_err"],
            fmt='o', markerfacecolor='none', markeredgecolor=COLOR_800,
            markeredgewidth=2, ecolor=COLOR_800, ms=10, lw=2, capsize=4)

# Projected Shared-Slope Linear Regressions
ax.plot(T_plot, fitline600, '--', color=COLOR_600, lw=3)
ax.plot(T_plot, fitline800, '--', color=COLOR_800, lw=3)

# Formatting Layout
ax.set_xlabel("Temperature (K)")
ax.set_ylabel("$\\Delta\\nu$ (Hz)")  # Safe LaTeX mathematical format
ax.set_xlim(284, 316)
ax.legend(frameon=False, loc="center left", bbox_to_anchor=(0.02, 0.60))

# FIXED: Strip top/right spines for journal style
ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()

# Save high-end outputs
PDF_OUT = os.path.join(FIGURE_DIR, "03a_dnu_vs_temperature.pdf")
PNG_OUT = os.path.join(FIGURE_DIR, "03a_dnu_vs_temperature.png")
plt.savefig(PDF_OUT, bbox_inches='tight')
plt.savefig(PNG_OUT, dpi=300, bbox_inches='tight')

print(f"✅ Figures written out cleanly:\n  👉 {PDF_OUT}\n  👉 {PNG_OUT}\n")
plt.close()
